[package]
name = "uwh-refbox"
version = "0.1.0"
authors = ["Tristan Debrunner <tpwd@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
embedded-graphics = "0.7.1"
embedded-graphics-simulator = "0.3.0"
env_logger = "0.6.1"
gdk = "0.12.0"
gio = "0.8.0"
glib = "0.9.1"
gtk = "0.8.0"
log = "0.4.6"
thiserror = "1.0.11"
toml = "0.5"
uwh-common = { version = "0.1.0", path = "../uwh-common"}
uwh-matrix-drawing = { version = "0.1.0", path = "../uwh-matrix-drawing"}

