[package]
name = "uwh-refbox"
version = "0.1.0"
authors = ["Tristan Debrunner <tpwd@me.com>"]
edition = "2018"

[features]
default = []
oldui = ["gdk", "gio", "glib", "gtk"]

[dependencies]
clap = "2.33.0"
embedded-graphics = "0.7.1"
embedded-graphics-simulator = "0.3.0"
eframe = "0.17.0"
env_logger = "0.6.1"
gdk = { version = "0.12.0", optional = true }
gio = { version = "0.8.0", optional = true }
glib = { version = "0.9.1", optional = true }
gtk = { version = "0.8.0", optional = true }
log = "0.4.6"
thiserror = "1.0.11"
toml = "0.5"
uwh-common = { version = "0.1.0", path = "../uwh-common"}
uwh-matrix-drawing = { version = "0.1.0", path = "../uwh-matrix-drawing"}

