language: rust
cache: cargo
rust: stable
jobs:
  includes:
    - stage: check
      name: Run checks
      addons:
        apt:
          packages: libgtk-3-dev
      install:
        - rustup component add rustfmt
        - rustup component add clippy
        - ci/cargo-try-install.sh cargo-audit
      script:
        - cargo fmt --all -- --check
        - cargo clippy --all -- --deny=warnings
        - cargo audit
    - stage: test
      name: test-linux
      addons:
        apt:
          packages: libgtk-3-dev
      script: cargo test --all
    - stage: test
      name: build-linux
      addons:
        apt:
          packages: libgtk-3-dev
      script: cargo build --all
    - stage: test
      name: test-mac
      os: osx
      addons:
        homebrew:
          packages: gtk+3
          update: true
      script: cargo test --all
    - stage: test
      name: build-mac
      os: osx
      addons:
        homebrew:
          packages: gtk+3
          update: true
      script: cargo build --all
