[target.aarch64-unknown-linux-gnu]
pre-build = [
    "dpkg --add-architecture $CROSS_DEB_ARCH",
    "apt-get update",
    "apt-get install -y --no-install-recommends libssl-dev:$CROSS_DEB_ARCH pkg-config:$CROSS_DEB_ARCH libasound2-dev:$CROSS_DEB_ARCH"
]