version: 2.1

jobs:
  check-build-debug:
    docker:
      - image: magycian/refbox-ci:1.66.1
        environment:
          CARGO_INCREMENTAL: 0
    steps:
      - checkout
      - restore_cache:
          key: v2-uwh-refbox-rs-1.66.1-{{ checksum "Cargo.lock" }}
          paths:
            - /home/circleci/.cache/sccache
            - /home/circleci/.cargo/registry/cache
            - /home/circleci/.cargo/git
            - /home/circleci/.cargo/.crates.toml
            - /home/circleci/.cargo/.crates2.json
            - target
      - run: cargo --version
      - run: rustc --version
      - run: cargo fmt -- --version
      - run: cargo clippy -- --version
      - run: cargo fmt --all -- --check
      - run: cargo clippy --all -- --deny=warnings
      - run: cargo clippy --all --no-default-features -- --deny=warnings
      - run: cargo audit --ignore RUSTSEC-2020-0056 --ignore RUSTSEC-2022-0048 --ignore RUSTSEC-2020-0071
      - run: cargo build --all
      - run: cargo build --all --no-default-features
      - run: cargo test --all
      - run: ./ci/clean-cache.sh
      - save_cache:
          key: v2-uwh-refbox-rs-1.66.1-{{ checksum "Cargo.lock" }}
          paths:
            - /home/circleci/.cache/sccache
            - /home/circleci/.cargo/registry/cache
            - /home/circleci/.cargo/git
            - /home/circleci/.cargo/.crates.toml
            - /home/circleci/.cargo/.crates2.json
            - target
  check-build-release:
    docker:
      - image: magycian/refbox-ci:1.66.1
        environment:
          CARGO_INCREMENTAL: 0
          RUSTFLAGS: "-D warnings"
    steps:
      - checkout
      - restore_cache:
          key: v2-uwh-refbox-rs-1.66.1-release-{{ checksum "Cargo.lock" }}
          paths:
            - /home/circleci/.cache/sccache
            - /home/circleci/.cargo/registry/cache
            - /home/circleci/.cargo/git
            - /home/circleci/.cargo/.crates.toml
            - /home/circleci/.cargo/.crates2.json
            - target
      - run: cargo --version
      - run: rustc --version
      - run: cargo fmt -- --version
      - run: cargo clippy -- --version
      - run: cargo fmt --all -- --check
      - run: cargo clippy --release --all -- --deny=warnings
      - run: cargo clippy --release --all --no-default-features -- --deny=warnings
      - run: cargo build --release --all
      - run: cargo build --release --all --no-default-features
      - run: cargo test --release --all
      - run: ./ci/clean-cache.sh
      - save_cache:
          key: v2-uwh-refbox-rs-1.66.1-release-{{ checksum "Cargo.lock" }}
          paths:
            - /home/circleci/.cache/sccache
            - /home/circleci/.cargo/registry/cache
            - /home/circleci/.cargo/git
            - /home/circleci/.cargo/.crates.toml
            - /home/circleci/.cargo/.crates2.json
            - target

workflows:
  check:
    jobs:
      - check-build-debug:
          filters:
            branches:
              only:
                - master
                - staging
                - trying
      - check-build-release:
          filters:
            branches:
              only:
                - master
                - staging
                - trying
