# syntax = docker/dockerfile:experimental
# The above line allows the tempfs workaround used below

# We'll just use the official Rust image rather than build our own from scratch
FROM arm32v7/rust:1.63.0-slim-bullseye

ENV KEYRINGS /usr/local/share/keyrings

RUN set -eux; \
    # Skipping all of the "recommended" cruft reduces total images size by ~300MiB
    apt-get update && apt-get install --no-install-recommends -y \
    libssl-dev \
    pkg-config \
    libasound2-dev

# Retrieve the std lib for the targets
RUN rustup target add armv7-unknown-linux-gnueabihf

# Update the cartes.io index
# Needs the tmpfs workaround due to a bug in qemu when emulating 32-bit arm on
# a 64-bit arm machine
RUN --security=insecure mkdir -p /root/.cargo && chmod 777 /root/.cargo && \
    mount -t tmpfs none /root/.cargo && \
    cargo search clap >> /dev/null

WORKDIR /workdir
