use super::*;

#[allow(non_camel_case_types)]
#[derive(Copy, Clone, Debug)]
pub enum Signal {
    bto_15s,
    bto_30s,
    bto_45s,
    bto_60s,
    bto_int,
    bs10_a,
    bs10_b,
    bs10_c,
    bs10_d,
    bs10_e,
    bs10_f,
    bs10_g,
    bs1_a,
    bs1_b,
    bs1_c,
    bs1_d,
    bs1_e,
    bs1_f,
    bs1_g,
    wto_15s,
    wto_30s,
    wto_45s,
    wto_60s,
    wto_int,
    ws10_a,
    ws10_b,
    ws10_c,
    ws10_d,
    ws10_e,
    ws10_f,
    ws10_g,
    ws1_a,
    ws1_b,
    ws1_c,
    ws1_d,
    ws1_e,
    ws1_f,
    ws1_g,
    m10_a,
    m10_b,
    m10_c,
    m10_d,
    m10_e,
    m10_f,
    m10_g,
    m1_a,
    m1_b,
    m1_c,
    m1_d,
    m1_e,
    m1_f,
    m1_g,
    s10_a,
    s10_b,
    s10_c,
    s10_d,
    s10_e,
    s10_f,
    s10_g,
    s1_a,
    s1_b,
    s1_c,
    s1_d,
    s1_e,
    s1_f,
    s1_g,
    rto_ind,
    bto_ind,
    wto_ind,
    fst_hlf,
    hlf_tm,
    snd_hlf,
    overtime,
    sdn_dth,
    colon,
}

impl Index<Signal> for DisplayState {
    type Output = bool;

    fn index(&self, signal: Signal) -> &Self::Output {
        match signal {
            Signal::bto_15s => &self.b_timeout_time.fifteen,
            Signal::bto_30s => &self.b_timeout_time.thirty,
            Signal::bto_45s => &self.b_timeout_time.forty_five,
            Signal::bto_60s => &self.b_timeout_time.sixty,
            Signal::bto_int => &self.b_timeout_time.int,
            Signal::bs10_a => &self.b_score_tens.a,
            Signal::bs10_b => &self.b_score_tens.b,
            Signal::bs10_c => &self.b_score_tens.c,
            Signal::bs10_d => &self.b_score_tens.d,
            Signal::bs10_e => &self.b_score_tens.e,
            Signal::bs10_f => &self.b_score_tens.f,
            Signal::bs10_g => &self.b_score_tens.g,
            Signal::bs1_a => &self.b_score_ones.a,
            Signal::bs1_b => &self.b_score_ones.b,
            Signal::bs1_c => &self.b_score_ones.c,
            Signal::bs1_d => &self.b_score_ones.d,
            Signal::bs1_e => &self.b_score_ones.e,
            Signal::bs1_f => &self.b_score_ones.f,
            Signal::bs1_g => &self.b_score_ones.g,
            Signal::wto_15s => &self.w_timeout_time.fifteen,
            Signal::wto_30s => &self.w_timeout_time.thirty,
            Signal::wto_45s => &self.w_timeout_time.forty_five,
            Signal::wto_60s => &self.w_timeout_time.sixty,
            Signal::wto_int => &self.w_timeout_time.int,
            Signal::ws10_a => &self.w_score_tens.a,
            Signal::ws10_b => &self.w_score_tens.b,
            Signal::ws10_c => &self.w_score_tens.c,
            Signal::ws10_d => &self.w_score_tens.d,
            Signal::ws10_e => &self.w_score_tens.e,
            Signal::ws10_f => &self.w_score_tens.f,
            Signal::ws10_g => &self.w_score_tens.g,
            Signal::ws1_a => &self.w_score_ones.a,
            Signal::ws1_b => &self.w_score_ones.b,
            Signal::ws1_c => &self.w_score_ones.c,
            Signal::ws1_d => &self.w_score_ones.d,
            Signal::ws1_e => &self.w_score_ones.e,
            Signal::ws1_f => &self.w_score_ones.f,
            Signal::ws1_g => &self.w_score_ones.g,
            Signal::m10_a => &self.time_m_tens.a,
            Signal::m10_b => &self.time_m_tens.b,
            Signal::m10_c => &self.time_m_tens.c,
            Signal::m10_d => &self.time_m_tens.d,
            Signal::m10_e => &self.time_m_tens.e,
            Signal::m10_f => &self.time_m_tens.f,
            Signal::m10_g => &self.time_m_tens.g,
            Signal::m1_a => &self.time_m_ones.a,
            Signal::m1_b => &self.time_m_ones.b,
            Signal::m1_c => &self.time_m_ones.c,
            Signal::m1_d => &self.time_m_ones.d,
            Signal::m1_e => &self.time_m_ones.e,
            Signal::m1_f => &self.time_m_ones.f,
            Signal::m1_g => &self.time_m_ones.g,
            Signal::s10_a => &self.time_s_tens.a,
            Signal::s10_b => &self.time_s_tens.b,
            Signal::s10_c => &self.time_s_tens.c,
            Signal::s10_d => &self.time_s_tens.d,
            Signal::s10_e => &self.time_s_tens.e,
            Signal::s10_f => &self.time_s_tens.f,
            Signal::s10_g => &self.time_s_tens.g,
            Signal::s1_a => &self.time_s_ones.a,
            Signal::s1_b => &self.time_s_ones.b,
            Signal::s1_c => &self.time_s_ones.c,
            Signal::s1_d => &self.time_s_ones.d,
            Signal::s1_e => &self.time_s_ones.e,
            Signal::s1_f => &self.time_s_ones.f,
            Signal::s1_g => &self.time_s_ones.g,
            Signal::rto_ind => &self.rto_ind,
            Signal::bto_ind => &self.bto_ind,
            Signal::wto_ind => &self.wto_ind,
            Signal::fst_hlf => &self.fst_hlf,
            Signal::hlf_tm => &self.hlf_tm,
            Signal::snd_hlf => &self.snd_hlf,
            Signal::overtime => &self.overtime,
            Signal::sdn_dth => &self.sdn_dth,
            Signal::colon => &self.colon,
        }
    }
}
