[package]
name = "fonts"
version = "0.1.0"
authors = ["Tristan Debrunner <tpwd@me.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-graphics = "=0.6.0-alpha.2"
paste = "0.1"
