//! Resolves team names (by game number) and player names (by team name + cap number) from two
//! local CSV files, as an alternative to [`crate::portal::Directory`] for events with no Portal
//! access at all. See `docs/backlog/overlay-bridge-roster-from-local-file/NOTE.md`, "a second
//! case -- no Portal at all".
//!
//! **There is no reconciliation step here, unlike the Portal path.** The Portal's `Directory`
//! matches a `TeamId` the schedule assigns; a local file has no `TeamId` at all, so a team is
//! whatever name an organiser typed in both files, and the two files must agree on it exactly.
//! There is nothing to fuzzy-match against, because there is no second, authoritative source of
//! team names to reconcile a typo against -- the file *is* the record.
//!
//! **A bad row is skipped, not a load failure.** These files are authored by a tournament
//! volunteer in a spreadsheet, not generated by a machine, so an occasional malformed row (a
//! blank line, a typo'd cap number) is expected. Skipping it and loading everything else follows
//! the same "never blank the whole picture over one bad piece" contract `portal.rs` uses for a
//! malformed Portal response -- only the file failing to open or having the wrong columns at all
//! is treated as a real failure.

use std::{collections::HashMap, fmt, path::Path};

/// One team's roster: cap number to player name.
type TeamRoster = HashMap<u8, String>;

/// Resolves team and player names for one event from two local CSV files, loaded once at
/// startup (or whenever the operator points the bridge at a new pair of files -- see the status
/// page toggle). Read-only after construction: unlike [`crate::portal::Directory`], there is no
/// refresh-on-a-timer here, since a local file only changes when an operator edits it and
/// reloads, not on its own.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct LocalRoster {
    /// Game number to (black team name, white team name).
    schedule: HashMap<u32, (String, String)>,
    /// Team name to that team's roster.
    rosters: HashMap<String, TeamRoster>,
}

/// Why a CSV file couldn't be loaded at all. A malformed *row* inside an otherwise-readable file
/// is not one of these -- see the module doc -- this is only for the file itself being
/// unreadable or missing the columns every row needs.
#[derive(Debug)]
pub enum LoadError {
    Schedule(csv::Error),
    Roster(csv::Error),
}

impl fmt::Display for LoadError {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            LoadError::Schedule(e) => write!(f, "couldn't read the schedule CSV: {e}"),
            LoadError::Roster(e) => write!(f, "couldn't read the roster CSV: {e}"),
        }
    }
}

impl std::error::Error for LoadError {}

/// One row of the schedule CSV: `gameNumber,blackTeam,whiteTeam`. Field names match the JSON
/// feed's own `blackTeam`/`whiteTeam`, so there is one vocabulary for the same two concepts
/// across the file and the wire, not two.
#[derive(Debug, serde::Deserialize)]
struct ScheduleRow {
    #[serde(rename = "gameNumber")]
    game_number: u32,
    #[serde(rename = "blackTeam")]
    black_team: String,
    #[serde(rename = "whiteTeam")]
    white_team: String,
}

/// One row of the roster CSV: `team,capNumber,rosterName`. `capNumber`/`rosterName` match the
/// Portal's own roster field names (see `portal.rs`'s `parse_roster`) rather than inventing a
/// second vocabulary for the same two things. `team` is the new column a local file needs that
/// the Portal path doesn't: with no `TeamId`, a row has to name its own team directly.
#[derive(Debug, serde::Deserialize)]
struct RosterRow {
    team: String,
    #[serde(rename = "capNumber")]
    cap_number: u8,
    #[serde(rename = "rosterName")]
    roster_name: String,
}

impl LocalRoster {
    /// Loads both files. Fails only if either file can't be opened or read, or is missing the
    /// header row every data row needs (`csv`'s own error for both cases) -- an individual bad
    /// data row is skipped instead, per the module doc.
    pub fn load(schedule_path: &Path, roster_path: &Path) -> Result<Self, LoadError> {
        let schedule = load_schedule(schedule_path).map_err(LoadError::Schedule)?;
        let rosters = load_rosters(roster_path).map_err(LoadError::Roster)?;
        Ok(Self { schedule, rosters })
    }

    /// The black and white team names for `game_number`, or `None` if that game number isn't in
    /// the schedule file -- the caller's fallback is the same as the Portal path's: show
    /// whatever the refbox itself already reports (in this case, nothing, since a Manual-mode
    /// refbox never has a team name at all) rather than an error.
    pub fn team_names_for(&self, game_number: u32) -> Option<(&str, &str)> {
        let (black, white) = self.schedule.get(&game_number)?;
        Some((black.as_str(), white.as_str()))
    }

    /// `cap_number`'s name on `team_name`'s roster, or `None` if that team isn't in the roster
    /// file, or the cap number isn't on it -- the caller's fallback is to display the cap number
    /// with no name, same as the Portal path.
    pub fn player_name(&self, team_name: &str, cap_number: u8) -> Option<&str> {
        self.rosters
            .get(team_name)?
            .get(&cap_number)
            .map(String::as_str)
    }

    /// Every player on `team_name`'s roster, sorted by cap number -- for a pre-game reveal, which
    /// needs every player, not just the handful [`Self::player_name`] resolves for a current
    /// penalty, foul or warning. Empty if the team isn't in the roster file, never an error.
    pub fn full_roster(&self, team_name: &str) -> Vec<(u8, &str)> {
        let Some(roster) = self.rosters.get(team_name) else {
            return Vec::new();
        };
        let mut players: Vec<(u8, &str)> = roster
            .iter()
            .map(|(&cap, name)| (cap, name.as_str()))
            .collect();
        players.sort_unstable_by_key(|(cap, _)| *cap);
        players
    }
}

fn load_schedule(path: &Path) -> Result<HashMap<u32, (String, String)>, csv::Error> {
    let mut reader = csv::Reader::from_path(path)?;
    Ok(reader
        .deserialize::<ScheduleRow>()
        .filter_map(Result::ok)
        .map(|row| (row.game_number, (row.black_team, row.white_team)))
        .collect())
}

fn load_rosters(path: &Path) -> Result<HashMap<String, TeamRoster>, csv::Error> {
    let mut reader = csv::Reader::from_path(path)?;
    let mut rosters: HashMap<String, TeamRoster> = HashMap::new();
    for row in reader.deserialize::<RosterRow>().filter_map(Result::ok) {
        rosters
            .entry(row.team)
            .or_default()
            .insert(row.cap_number, row.roster_name);
    }
    Ok(rosters)
}

#[cfg(test)]
mod tests {
    use std::io::Write;

    use super::*;

    /// Writes `contents` to a fresh temp file and returns its path, kept alive for the
    /// duration of the `NamedTempFile` -- dropped (and deleted) at the end of the calling test.
    fn temp_csv(contents: &str) -> tempfile::NamedTempFile {
        let mut file = tempfile::NamedTempFile::new().expect("create a temp file");
        file.write_all(contents.as_bytes())
            .expect("write fixture CSV");
        file
    }

    const SCHEDULE_CSV: &str = "gameNumber,blackTeam,whiteTeam\n\
                                 1,Chengdu,Beijing\n\
                                 2,Beijing,Chengdu\n";

    const ROSTER_CSV: &str = "team,capNumber,rosterName\n\
                               Chengdu,2,Li Wei\n\
                               Chengdu,7,Zhang Min\n\
                               Beijing,2,Wang Fang\n";

    #[test]
    fn team_names_resolve_by_game_number() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path()).expect("should load");

        assert_eq!(local.team_names_for(1), Some(("Chengdu", "Beijing")));
        assert_eq!(local.team_names_for(2), Some(("Beijing", "Chengdu")));
    }

    #[test]
    fn an_unknown_game_number_has_no_team_names() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path()).expect("should load");

        assert_eq!(local.team_names_for(99), None);
    }

    #[test]
    fn player_names_resolve_by_team_name_and_cap_number() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path()).expect("should load");

        assert_eq!(local.player_name("Chengdu", 2), Some("Li Wei"));
        assert_eq!(local.player_name("Chengdu", 7), Some("Zhang Min"));
        assert_eq!(local.player_name("Beijing", 2), Some("Wang Fang"));
    }

    #[test]
    fn full_roster_returns_every_player_sorted_by_cap_number() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path()).expect("should load");

        assert_eq!(
            local.full_roster("Chengdu"),
            vec![(2, "Li Wei"), (7, "Zhang Min")]
        );
    }

    #[test]
    fn full_roster_for_an_unknown_team_is_empty() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path()).expect("should load");

        assert_eq!(local.full_roster("Nonexistent Team"), Vec::new());
    }

    #[test]
    fn an_unknown_team_or_cap_number_has_no_player_name() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path()).expect("should load");

        assert_eq!(local.player_name("Chengdu", 99), None);
        assert_eq!(local.player_name("Nonexistent Team", 2), None);
    }

    #[test]
    fn a_malformed_row_is_skipped_but_the_rest_of_the_file_still_loads() {
        let schedule = temp_csv(
            "gameNumber,blackTeam,whiteTeam\n\
             1,Chengdu,Beijing\n\
             notanumber,Bad,Row\n\
             2,Beijing,Chengdu\n",
        );
        let roster = temp_csv(ROSTER_CSV);
        let local = LocalRoster::load(schedule.path(), roster.path())
            .expect("a bad row must not fail the whole load");

        assert_eq!(local.team_names_for(1), Some(("Chengdu", "Beijing")));
        assert_eq!(local.team_names_for(2), Some(("Beijing", "Chengdu")));
    }

    #[test]
    fn a_missing_file_fails_to_load() {
        let roster = temp_csv(ROSTER_CSV);
        let result = LocalRoster::load(Path::new("/does/not/exist.csv"), roster.path());
        assert!(matches!(result, Err(LoadError::Schedule(_))));
    }

    #[test]
    fn loading_reports_which_file_failed() {
        let schedule = temp_csv(SCHEDULE_CSV);
        let result = LocalRoster::load(schedule.path(), Path::new("/does/not/exist.csv"));
        assert!(matches!(result, Err(LoadError::Roster(_))));
    }
}
