name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-windows:
    name: Build release on windows-latest
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2
    - name: Versions
      run: cargo --version && rustc --version && cargo fmt -- --version && cargo clippy -- --version
    - run: cargo build --release --bin refbox
    - uses: actions/upload-artifact@v4
      with:
        name: refbox-windows
        path: target/release/refbox.exe

  build-macos-arm:
    name: Build release on macos-latest for arm target
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-bundle from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-bundle
    - name: Versions
      run: cargo --version && rustc --version && cargo fmt -- --version && cargo clippy -- --version && cargo bundle --version
    - run: cargo bundle --release --target aarch64-apple-darwin -p refbox
    - uses: actions/upload-artifact@v4
      with:
        name: refbox-macos-arm
        path: target/aarch64-apple-darwin/release/bundle/osx/refbox.app

  build-macos-x86:
    name: Build release on macos-latest for x86 target
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2
    - name: Install cargo-bundle from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cargo-bundle
    - name: Versions
      run: cargo --version && rustc --version && cargo fmt -- --version && cargo clippy -- --version && cargo bundle --version
    - run: rustup target add x86_64-apple-darwin
    - run: cargo bundle --release --target x86_64-apple-darwin -p refbox
    - uses: actions/upload-artifact@v4
      with:
        name: refbox-macos-x86
        path: target/x86_64-apple-darwin/release/bundle/osx/refbox.app

  build-rpi:
    name: Build release on linux for aarch64 (Raspberry Pi)
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
    - uses: Swatinem/rust-cache@v2
    - name: Install cross from crates.io
      uses: baptiste0928/cargo-install@v3
      with:
        crate: cross
    - name: Versions
      run: cargo --version && rustc --version && cargo fmt -- --version && cargo clippy -- --version && cross --version
    - run: cross build --release --target aarch64-unknown-linux-gnu -p refbox
    - uses: actions/upload-artifact@v4
      with:
        name: refbox-rpi
        path: target/aarch64-unknown-linux-gnu/release/refbox

  upload-release:
    name: Upload release artifacts
    runs-on: ubuntu-latest

    needs: [build-windows, build-macos-arm, build-macos-x86, build-rpi]

    steps:
    - uses: actions/download-artifact@v5
      with:
        name: refbox-windows
        path: release/Windows/refbox.exe
    - uses: actions/download-artifact@v5
      with:
        name: refbox-macos-arm
        path: release/Mac\ (Arm processor)/refbox.app
    - uses: actions/download-artifact@v5
      with:
        name: refbox-macos-x86
        path: release/Mac\ (Intel processor)/refbox.app
    - uses: actions/download-artifact@v5
      with:
        name: refbox-rpi
        path: release/Raspberry\ Pi
    - name: Download PDFs from Google Drive
      run: |
        curl -L "https://drive.usercontent.google.com/download?id=1Momxds_2oyPTEZHgcuSxnTxI_HbGeaN8&export=download" -o "release/Getting Started Guide - English.pdf"
        curl -L "https://drive.usercontent.google.com/download?id=13eHCCmBH-IEUwIODaqpbbz_LiZQBBh0p&export=download" -o "release/Getting Started Guide - Spanish (Guía de Inicio).pdf"
        curl -L "https://drive.usercontent.google.com/download?id=1sJTdKHKjul6Pa7eV44APEQBFaxwQSvYy&export=download" -o "release/Providing App Credentials - English.pdf"
        curl -L "https://drive.usercontent.google.com/download?id=1skrUYTEYBgHs4T-dl3AobwklfJR3ZGE1&export=download" -o "release/Refbox User Manual.pdf"
        curl -L "https://drive.usercontent.google.com/download?id=1FLtJwc8gb5vuSRVPUNLxKhT1ufcOSa-w&export=download" -o "release/Refbox User Manual with Fouls.pdf"
    - name: Zip release
      run: cd release && zip -r ../refbox.zip .
    - uses: softprops/action-gh-release@v2
      with:
        files: refbox.zip
        draft: true
        generate_release_notes: true
